# SPDX-License-Identifier: Apache-2.0
# Start empty: use OpenShift default SCCs (restricted-v2). Add manifests
# only after a failure is proven on 1.19.1 — do NOT reintroduce
# opendesk-anyuid-seccomp from prior overlays.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
