# SPDX-FileCopyrightText: 2024-2026 Zentrum für Digitale Souveränität der Öffentlichen Verwaltung (ZenDiS) GmbH
# SPDX-FileCopyrightText: 2024 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: "kyverno.io/v1"
kind: "ClusterPolicy"
metadata:
  name: "require-digest"
  annotations:
    policies.kyverno.io/title: "Require digest for image."
    policies.kyverno.io/subject: "Pod"
    policies.kyverno.io/description: >-
      To ensure that containers are not compromised in container registry by pushing malicious code to the same tag, it
      is required to reference images by setting a sha256 hashed digest.
spec:
  background: true
  rules:
    - match:
        resources:
          kinds:
            - "Pod"
      name: "require-digest"
      validate:
        message: "An image digest is required."
        pattern:
          spec:
            =(ephemeralContainers):
              - image: "*@sha256:*"
            =(initContainers):
              - image: "*@sha256:*"
            containers:
              - image: "*@sha256:*"
  validationFailureAction: "audit"
...
